# Generated by Django 2.2.4 on 2022-04-09 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('USER', 'USER'), ('DELIVERY', 'DELIVERY')], default='USER', max_length=100, null=True)),
                ('image', models.ImageField(default='default.png', upload_to='profile_pics')),
                ('instituteName', models.CharField(max_length=100, null=True)),
                ('instituteType', models.CharField(choices=[('Individual', 'Individual'), ('NGO', 'NGO'), ('Private', 'Private'), ('Residential', 'Residential'), ('Event', 'Event'), ('Others', 'Others')], default='Others', max_length=100, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('acceptanceRate', models.FloatField(default=0, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
