# Generated by Django 2.2.4 on 2022-04-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='walletPublicAddress',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
    ]
