# Generated by Django 2.2.4 on 2022-04-09 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profilemodel_walletpublicaddress'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='organization',
        ),
        migrations.AddField(
            model_name='item',
            name='isOrdered',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='isQualityOK',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='isQuantityOK',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='ordering_organization',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordering_organization', to='users.ProfileModel'),
        ),
        migrations.AddField(
            model_name='item',
            name='posting_organization',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posting_organization', to='users.ProfileModel'),
        ),
    ]
