# Generated by Django 2.2.4 on 2022-04-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220409_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='isDelivered',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='walletPublicAddress',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
    ]
