# Generated by Django 2.2.4 on 2022-04-09 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profilemodel_walletpublicaddress'),
        ('posts', '0004_item_deliveredby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='deliveredBY',
        ),
        migrations.AddField(
            model_name='item',
            name='deliveredBy',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveredBy', to='users.ProfileModel'),
        ),
    ]
