# Generated by Django 2.2.4 on 2022-04-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20220409_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='isChecked',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
