# Generated by Django 2.2.4 on 2022-04-10 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20220409_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='profile_pics'),
        ),
    ]
